extends Node

const EQUIPMENT_TAGS = {
	"hardpoint_types":[
		"HARDPOINT_SAIL_MIKE",
		"HARDPOINT_SAIL_WEAPON"
	],
	"slot_defaults":{
		"HARDPOINT_SAIL_MIKE":[
			"EQUIPMENT_TURRETS",
			"EQUIPMENT_MICROWAVES",
			"EQUIPMENT_NANODRONES"
		],
		"HARDPOINT_SAIL_WEAPON":[
			"EQUIPMENT_MASS_DRIVERS",
			"EQUIPMENT_NANODRONES",
			"EQUIPMENT_IRON_THROWERS",
			"EQUIPMENT_MINING_LASERS",
			"EQUIPMENT_IMPACT_ABSORBER"
		]
	}
}
